---
title: "Untitled"
author: "Annnakin"
date: "3/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install packages
```{r}
rm(list=ls())
graphics.off()

suppressMessages({
  library(tidyr)
  library(tibble)
  library(dplyr)
  library(tidyverse)
  library(RColorBrewer)
  library(pheatmap)
  library(randomForest)
  library(parallel)
  library(gridExtra)
  library(grid)
  library(ComplexHeatmap) ## Source: https://github.com/jokergoo/ComplexHeatmap 
})
#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")

#BiocManager::install("pvca")
```

# Load and explore data
```{r}
file_idx="_D70_" ## ID of your FileName
source(file.path(getwd(),"1-pvca.R"))
empty.plot <- function() plot(NA,NA,xlim=c(0,1),ylim=c(0,1),axes = F,xlab="",ylab="")

data = read.csv("ObjectsAll_LRRK2_PD.csv",as.is = T,check.names = F)
janitor::tabyl(data, Condition, Cellline, Day)
# Data to setup the model
Data = data %>% filter(Day %in% c("d70"))  ## Choose the time point
janitor::tabyl(Data, Condition, Cellline)

metadata = Data[,1:which(colnames(Data) == "LRRK2")]
rownames(metadata) = metadata$ID
exprs = Data[,(which(colnames(Data) == "LRRK2")+1):ncol(Data)]
rownames(exprs) = metadata$ID
exprs = exprs[,order(colnames(exprs))]
#exprs=log(exprs)
dplyr::na_if(exprs,  Inf) -> exprs
dplyr::na_if(exprs, -Inf) -> exprs
range(exprs)
dim(exprs)

```


# Splcos
```{r}
spl.cols = c(
  H     = "lightblue",
  PD    = "red"
)[metadata$Condition]

feature.names = c(
    FOXA2ByNuc='FOXA2+/Nuclei',
    FOXA2MaskSum ='FOXA2 Sum',
    Links    = 'TH Links',
    Nodes  = 'TH Nodes',
    NonTH_FOXA2   = 'NonTH_FOXA2+/Nuclei',
    NonTH_FOXA2byNucPerim = 'PercentNonTH_FOXA2+',
    NucMaskHigh    = 'Nuclei dead mask',
    NucMaskSum     = 'Nuclei mask',
    SkelTH         = 'TH skeleton',
    TH_FOXA2       = 'TH+/FOXA2+/Nuclei',
    TH_FOXA2byNucPerim     = 'PercentTH+/FOXA2+',
    THByNuc   = 'TH+/Nuclei',
    THFragmentation='TH fragmentation',
    THMaskSum      = 'TH mask',
    THPercent      = 'Percentage TH'
)
exprs = exprs[,names(feature.names)]

fact.cols = list(
  LRRK2   = c("WT" = "gold1", "MUT" = "gold4"),
  Condition = c(H="lightblue",PD="red"),
  Day  = c("d10"="black","d35"="darkgrey","d70"="grey50")
)
```

# QC
```{r}
explore.file = file.path("Results",paste0(Sys.Date(), file_idx,"QC.pdf"))

pdf(explore.file,width = 11.4,height = 8.4)
par(mar=c(10,6,6,6))
boxplot(
  t(exprs),
  col=spl.cols,
  las=2,
  main="Boxplot of observations - Raw data",
  cex.axis=.5
)


dens = apply(exprs,1,density)
dx = sapply(dens,function(x)x$x)
dy = sapply(dens,function(x)x$y)
matplot(
  dx,dy,
  col=spl.cols,
  lty=1,
  type='l',
  lwd=1,
  main="Density plot of observations - Raw data"
)
legend(
  "topright",
  legend = names(fact.cols$Condition),
  fill   = fact.cols$Condition,
  bty="n"
)

# PVCA
########## All features - PVCA
batch.factors = c("Cellline","Passage","Condition","LRRK2", "Experiment") ## Name your experimental factors
cmb = NULL
if(length(batch.factors) > 1) {
  cmb = combn(batch.factors,2)
  cmb = paste(cmb[1,],cmb[2,],sep=":")
  cmb = cmb[!grepl("Replicate",cmb)]
}
pct_threshold <- 0.9
model.func = paste("(1|", c(batch.factors,cmb), ")", sep = "")
pvcaObj <- pvca(
  as.matrix(t(exprs)),
  metadata,
  batch.factors,
  pct_threshold,
  model.func
)
fac.order = c(batch.factors,cmb,"resid")

par(mar=c(10,6,6,6))
bp <- barplot(
  pvcaObj$dat[match(fac.order,pvcaObj$label)], xlab = "",
  ylab = "Weighted average proportion variance",
  ylim= c(0,1.1),col = c("blue"), las=2,
  main="PVCA estimation bar chart"
)
text(bp,-0.02, srt = 45, adj= 1, xpd = TRUE, labels = fac.order, cex=0.7)
values = pvcaObj$dat
new_values = round(values , 3)
text(
  bp,
  pvcaObj$dat[match(fac.order,pvcaObj$label)],
  labels = new_values[match(fac.order,pvcaObj$label)], pos=3, cex = .8
)

pct_threshold <- 0.9
model.func = paste("(1|", c(batch.factors), ")", sep = "")
pvcaObj <- pvca(
  t(exprs)[,],
  metadata[,],
  batch.factors,
  pct_threshold,
  model.func
)
fac.order = c(batch.factors,"resid")

par(mar=c(10,6,6,6))
bp <- barplot(
  pvcaObj$dat[match(fac.order,pvcaObj$label)], xlab = "",
  ylab = "Weighted average proportion variance",
  ylim= c(0,1.1),col = c("blue"), las=2,
  main="PVCA estimation bar chart"
)
text(bp,-0.02, srt = 45, adj= 1, xpd = TRUE, labels = fac.order, cex=0.7)
values = pvcaObj$dat
new_values = round(values , 3)
text(
  bp,
  pvcaObj$dat[match(fac.order,pvcaObj$label)],
  labels = new_values[match(fac.order,pvcaObj$label)],
  pos=3,
  cex = .8
)
# Heatmap1
spl.cor = cor(t(exprs))
fHclust = hclust(as.dist(1-spl.cor))
sHclust = hclust(as.dist(1-spl.cor))

Heatmap(
  spl.cor,
  cluster_rows = fHclust,
  cluster_columns  = sHclust,
  top_annotation = HeatmapAnnotation(Condition=metadata$Condition, 
                                     Mutation = metadata$Mutation,
                                     Passage = metadata$Passage,
                                     # metadata[,c("Condition","LRRK2","Day")],
                                     col = fact.cols,
                                     show_annotation_name = T
  ),
  show_column_names = F,
  show_row_names = F
)


# Heatmap 2 (scaled)

spl.cor = cor(t(scale(exprs)))
fHclust = hclust(as.dist(1-spl.cor))
sHclust = hclust(as.dist(1-spl.cor))

Heatmap(
  spl.cor,
  cluster_rows = fHclust,
  cluster_columns  = sHclust,
  top_annotation = HeatmapAnnotation(Condition=metadata$Condition, 
                                     Mutation = metadata$Mutation,
                                     Passage = metadata$Passage,
                                     col = fact.cols,
                                     show_annotation_name = T
  ),
  show_column_names = F,
  show_row_names = F
)
dev.off()
```




# RF Requirement
```{r}
########### B. Random Forest/ML

#### 0. Requirement
set.seed(123)
nrows = nrow(exprs)
nfolds = 5 # 5-fold CV
cv_times = 10 # 10 x 5-fold CV

table(metadata$Condition)
folds_ll = lapply(1:cv_times,function(zz) lapply(
  split(1:nrows,metadata$Condition),
  function(x){
    split(x,sample(cut_number(x,n=nfolds,label=F)))
  }
))

lapply(folds_ll,lapply,sapply,length)
foldss = lapply(folds_ll,function(folds_l) mapply(
  function(a,b){
    sort(unlist(
      c(folds_l[[1]][a],folds_l[[2]][b])
    ))
  },
  sample(1:5),
  sample(1:5),
  SIMPLIFY = F
))


```

# Condition
```{r}
pdf.output = file.path("Results",paste0(Sys.Date(),file_idx, "ML_RF.pdf"))
pdf(pdf.output,width = 13,height = 8.4)

##### 1. Condition
empty.plot()
text(.5,.5,"******* Condition *******",cex=2)

RF = list()
### 1. Level per fold"
for(idx in 1:length(foldss)){
  folds = foldss[[idx]]
  cat("Run ",idx,"/10\n")
  
  dF = data.frame(Condition = metadata[,"Condition"],exprs)
  dF[!sapply(dF, is.numeric)] = lapply(dF[!sapply(dF, is.numeric)],as.factor)
  
  ## Prediction with RandomForest
  rF.list = mclapply(1:length(folds),function(i){
    tx   = sort(unlist(folds[-i]))
    test = folds[[i]]
    rF   = randomForest(Condition ~., data=dF[tx,])
    pred = predict(rF,dF[test,])
    list(
      rF = rF,
      accuracy   = mean(dF$Condition[test] == pred),
      importance = rF$importance[order(rF$importance, decreasing = T),],
      confusion  = table(Obs = dF$Condition[test], pred = pred),
     TN = table(Obs = dF$Condition[test], pred = pred)[1,1],
     TP = table(Obs = dF$Condition[test], pred = pred)[2,2],
     FN = table(Obs = dF$Condition[test], pred = pred)[2,1],
     FP = table(Obs = dF$Condition[test], pred = pred)[1,2],
     sensitivity = (table(Obs = dF$Condition[test], pred = pred)[2,2])/ ((table(Obs = dF$Condition[test], pred = pred)[2,2]) + (table(Obs = dF$Condition[test], pred = pred)[2,1])),
     specificity = (table(Obs = dF$Condition[test], pred = pred)[1,1]) / ((table(Obs = dF$Condition[test], pred = pred)[1,1])+(table(Obs = dF$Condition[test], pred = pred)[1,2]))

    )
  },
  mc.cores= detectCores() - 1
  )
  RF[[idx]] = rF.list
  rm(folds)
}

### Summary
mat = round(do.call(rbind, lapply(RF, sapply,function(x) x$accuracy)),2)
colnames(mat) = paste0('Fold ',1:nfolds)
rownames(mat) = paste0('Run ',1:cv_times)

mat2 = round(do.call(rbind, lapply(RF, sapply,function(x) x$sensitivity)),2)
colnames(mat2) = paste0('Fold ',1:nfolds)
rownames(mat2) = paste0('Run ',1:cv_times)

mat3 = round(do.call(rbind, lapply(RF, sapply,function(x) x$specificity)),2)
colnames(mat3) = paste0('Fold ',1:nfolds)
rownames(mat3) = paste0('Run ',1:cv_times)


## Accuracy
par(mfrow=c(1,1))
empty.plot()
text(.5,.97,paste0("Accuracy (TP+TN)/(TP+FP+TN+FN)"),cex=2)
#True Positive +True Negative)/ (True Positive+ False Positive + True Negative + False Negative)
text( .5,.90,paste0("Random Forest (10x 5-fold CV)"),cex=1.2)
text(.5,.86,paste0("\nMean of accuracy = ",round(mean(rowMeans(mat)),2)," ± ",round(sd(rowMeans(mat)),2),"\n"),cex=1.2)
grid.table(mat)
layout(mat = matrix(c(1,2)),heights = c(.2,.8))


##Sensitivity
par(mfrow=c(1,1))
empty.plot()
text(.5,.97,paste0("Sensitivity TP/(TP+FN)"),cex=2)
text( .5,.90,paste0("Random Forest (10x 5-fold CV)"),cex=1.2)
text(.5,.86,paste0("\nMean of sensitivity = ",round(mean(rowMeans(mat2)),2),
    " ± ",round(sd(rowMeans(mat2)),2),"\n"),cex=1.2)
grid.table(mat2)
layout(mat = matrix(c(1,2)),heights = c(.2,.8))


##Specificity
par(mfrow=c(1,1))
empty.plot()
text(.5,.97,paste0("Specificity TN/(TN+FP)"),cex=2)
text( .5,.90,paste0("Random Forest (10x 5-fold CV)"),cex=1.2)
text(.5,.86,paste0("\nMean of specificity = ",round(mean(rowMeans(mat3)),2),
    " ± ",round(sd(rowMeans(mat3)),2),"\n"),cex=1.2)
grid.table(mat3)
layout(mat = matrix(c(1,2)),heights = c(.2,.8))


par(mar=c(4,6,2,6),xpd=T)
plot(NA,NA,xlim=c(0,1),ylim=c(0,1),axes = F,xlab="",ylab="")
text(.5,.005,paste0(
    "Distribution of RF accuracies\nover 10x 5-fold CV\n",
    "Grand mean = ",round(mean(rowMeans(mat)),2),
    " ± ",round(sd(rowMeans(mat)),2),"\n"),cex=1.2)
boxplot(lapply(RF, function(x) sapply(x,function(y) y$accuracy)))

df = data.frame(
  Run = rownames(mat),
  Accuracy = rowMeans(mat),
  sd = apply(mat,1,sd)
)
par(mfrow=c(1,1),mar=c(6,6,6,4))
x = barplot(
  df$Accuracy,
  ylim=c(0,max(df$Accuracy + df$sd)+.05),
  ylab = "Average accuracy",
  main=paste0(
    "\n\nAverage accuracy\n(10x 5-fold CV)\n",
    "Grand mean = ",round(mean(rowMeans(mat)),2),
    " ± ",
    round(sd(rowMeans(mat)),2),"\n"
  ),main.cex=1.2
)
for(i in 1:nrow(df))
  lines(c(x[i],x[i]),with(df,c(Accuracy[i]-sd[i],Accuracy[i]+sd[i])))
for(i in 1:nrow(df))
  lines(c(x[i]-.1,x[i] + .1),rep(with(df,c(Accuracy[i]-sd[i])),2))
for(i in 1:nrow(df))
  lines(c(x[i]-.1,x[i] + .1),rep(with(df,c(Accuracy[i]+sd[i])),2))
axis(1,x,df$Run,las=2)
rm(x,df)
vars = names(RF[[1]][[1]]$importance)
idx = 0
imports = list()
for(rF.list in RF)
  imports[[idx <<- idx + 1]] = sapply(rF.list, function(x) x$importance[vars])
imports = do.call(cbind, lapply(imports, function(x) x))

rownames(imports)  = feature.names[rownames(imports)]


par(mfrow=c(1,1),mar=c(4,10,6,4))
barplot(
  sort(rowMeans(imports),decreasing = F),
  main="\nRF - Condition - Feature importances",
  horiz = T,las=2,xlab = "Feature importances\n"
)
model1 = list(
  RF = RF,
  imports = imports
)
rm(mat,RF,imports,vars,mat,idx)
dev.off()
Biobase::openPDF(pdf.output)
```
